package com.sefin_rrhh.pr_rrhh_solicitudes;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitud implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id_solicitud")
	public Integer id_solicitud;
	@org.kie.api.definition.type.Label("id_exp_identificaciones")
	public Integer id_exp_identificaciones;
	@org.kie.api.definition.type.Label("nombre_documento")
	public java.lang.String nombre_documento;
	@org.kie.api.definition.type.Label("id_estado_sol")
	public Integer id_estado_sol;
	@org.kie.api.definition.type.Label("estado_sol_desc")
	public java.lang.String estado_sol_desc;
	@org.kie.api.definition.type.Label("id_tipo_sol")
	public Integer id_tipo_sol;
	@org.kie.api.definition.type.Label("tipo_sol_descripcion")
	public java.lang.String tipo_sol_descripcion;
	@org.kie.api.definition.type.Label("id_solicitud_ref")
	public Integer id_solicitud_ref;
	@org.kie.api.definition.type.Label("solicitud_referencia_desc")
	public java.lang.String solicitud_referencia_desc;
	@org.kie.api.definition.type.Label("verificado")
	public Integer verificado;
	@org.kie.api.definition.type.Label("vigente")
	public Integer vigente;
	@org.kie.api.definition.type.Label("observaciones")
	public java.lang.String observaciones;
	@org.kie.api.definition.type.Label("usu_cre")
	public java.lang.String usu_cre;
	@org.kie.api.definition.type.Label("fec_cre")
	public java.lang.String fec_cre;
	@org.kie.api.definition.type.Label("usu_mod")
	public java.lang.String usu_mod;
	@org.kie.api.definition.type.Label("fec_mod")
	public java.lang.String fec_mod;
	@org.kie.api.definition.type.Label(value = "numero_identidad")
	private java.lang.String numero_identidad;
	public java.lang.String getNombre_documento() {
		return nombre_documento;
	}
	public void setNombre_documento(java.lang.String nombre_documento) {
		this.nombre_documento = nombre_documento;
	}
	public java.lang.String getEstado_sol_desc() {
		return estado_sol_desc;
	}
	public void setEstado_sol_desc(java.lang.String estado_sol_desc) {
		this.estado_sol_desc = estado_sol_desc;
	}
	public java.lang.String getTipo_sol_descripcion() {
		return tipo_sol_descripcion;
	}
	public void setTipo_sol_descripcion(java.lang.String tipo_sol_descripcion) {
		this.tipo_sol_descripcion = tipo_sol_descripcion;
	}
	public java.lang.String getSolicitud_referencia_desc() {
		return solicitud_referencia_desc;
	}
	public void setSolicitud_referencia_desc(
			java.lang.String solicitud_referencia_desc) {
		this.solicitud_referencia_desc = solicitud_referencia_desc;
	}
	public java.lang.String getObservaciones() {
		return observaciones;
	}
	public void setObservaciones(java.lang.String observaciones) {
		this.observaciones = observaciones;
	}
	public java.lang.String getUsu_cre() {
		return usu_cre;
	}
	public void setUsu_cre(java.lang.String usu_cre) {
		this.usu_cre = usu_cre;
	}
	public java.lang.String getFec_cre() {
		return fec_cre;
	}
	public void setFec_cre(java.lang.String fec_cre) {
		this.fec_cre = fec_cre;
	}
	public java.lang.String getUsu_mod() {
		return usu_mod;
	}
	public void setUsu_mod(java.lang.String usu_mod) {
		this.usu_mod = usu_mod;
	}
	public java.lang.String getFec_mod() {
		return fec_mod;
	}
	public void setFec_mod(java.lang.String fec_mod) {
		this.fec_mod = fec_mod;
	}
	public Solicitud() {
	}
	public java.lang.Integer getId_solicitud() {
		return this.id_solicitud;
	}
	public void setId_solicitud(java.lang.Integer id_solicitud) {
		this.id_solicitud = id_solicitud;
	}
	public java.lang.Integer getId_exp_identificaciones() {
		return this.id_exp_identificaciones;
	}
	public void setId_exp_identificaciones(
			java.lang.Integer id_exp_identificaciones) {
		this.id_exp_identificaciones = id_exp_identificaciones;
	}
	public java.lang.Integer getId_estado_sol() {
		return this.id_estado_sol;
	}
	public void setId_estado_sol(java.lang.Integer id_estado_sol) {
		this.id_estado_sol = id_estado_sol;
	}
	public java.lang.Integer getId_tipo_sol() {
		return this.id_tipo_sol;
	}
	public void setId_tipo_sol(java.lang.Integer id_tipo_sol) {
		this.id_tipo_sol = id_tipo_sol;
	}
	public java.lang.Integer getId_solicitud_ref() {
		return this.id_solicitud_ref;
	}
	public void setId_solicitud_ref(java.lang.Integer id_solicitud_ref) {
		this.id_solicitud_ref = id_solicitud_ref;
	}
	public java.lang.Integer getVerificado() {
		return this.verificado;
	}
	public void setVerificado(java.lang.Integer verificado) {
		this.verificado = verificado;
	}
	public java.lang.Integer getVigente() {
		return this.vigente;
	}
	public void setVigente(java.lang.Integer vigente) {
		this.vigente = vigente;
	}
	public java.lang.String getNumero_identidad() {
		return this.numero_identidad;
	}
	public void setNumero_identidad(java.lang.String numero_identidad) {
		this.numero_identidad = numero_identidad;
	}
	public Solicitud(java.lang.Integer id_solicitud,
			java.lang.Integer id_exp_identificaciones,
			java.lang.String nombre_documento, java.lang.Integer id_estado_sol,
			java.lang.String estado_sol_desc, java.lang.Integer id_tipo_sol,
			java.lang.String tipo_sol_descripcion,
			java.lang.Integer id_solicitud_ref,
			java.lang.String solicitud_referencia_desc,
			java.lang.Integer verificado, java.lang.Integer vigente,
			java.lang.String observaciones, java.lang.String usu_cre,
			java.lang.String fec_cre, java.lang.String usu_mod,
			java.lang.String fec_mod, java.lang.String numero_identidad) {
		this.id_solicitud = id_solicitud;
		this.id_exp_identificaciones = id_exp_identificaciones;
		this.nombre_documento = nombre_documento;
		this.id_estado_sol = id_estado_sol;
		this.estado_sol_desc = estado_sol_desc;
		this.id_tipo_sol = id_tipo_sol;
		this.tipo_sol_descripcion = tipo_sol_descripcion;
		this.id_solicitud_ref = id_solicitud_ref;
		this.solicitud_referencia_desc = solicitud_referencia_desc;
		this.verificado = verificado;
		this.vigente = vigente;
		this.observaciones = observaciones;
		this.usu_cre = usu_cre;
		this.fec_cre = fec_cre;
		this.usu_mod = usu_mod;
		this.fec_mod = fec_mod;
		this.numero_identidad = numero_identidad;
	}
}