package com.sefin_rrhh.pr_rrhh_solicitudes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GlobalVar implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("mail_method")
	private java.lang.String mail_method;
	@org.kie.api.definition.type.Label("mail_user")
	private java.lang.String mail_user;
	@org.kie.api.definition.type.Label("mail_attribute")
	private java.lang.String mail_attribute;
	@org.kie.api.definition.type.Label("mail_type")
	private java.lang.String mail_type;
	@org.kie.api.definition.type.Label("mail_keyvalue")
	private java.lang.String mail_keyvalue;

	@org.kie.api.definition.type.Label("document_method")
	private java.lang.String document_method;
	@org.kie.api.definition.type.Label("document_document")
	private java.lang.String document_document;
	@org.kie.api.definition.type.Label("document_okp")
	private java.lang.String document_okp = "reversa_vacacion";
	@org.kie.api.definition.type.Label("document_return")
	private java.lang.String document_return;
	@org.kie.api.definition.type.Label("proc_url")
	private java.lang.String proc_url = "http://api-rrhh-expe-reversa-vacaciones-desa-api-rrhh-pool.apps.galel.sefin.gob.hn/api";
	@org.kie.api.definition.type.Label("proc_method")
	private java.lang.String proc_method;
	@org.kie.api.definition.type.Label("opcion")
	private java.lang.String opcion;
	@org.kie.api.definition.type.Label("expe_method")
	private java.lang.String expe_method;
	@org.kie.api.definition.type.Label("document_path")
	private java.lang.String document_path;
	@org.kie.api.definition.type.Label("uuidPlantillaAusencias")
	private java.lang.String uuidPlantillaAusencias = "161d6c23-e86d-4204-8ad7-e1ccdc880cfe";

	@org.kie.api.definition.type.Label("uuidPlantillasLlegadasTarde")
	private java.lang.String uuidPlantillasLlegadasTarde = "7e03057e-72ea-46ec-8244-f713b9885cc6";

	@org.kie.api.definition.type.Label("uuidPlantillaCitasInjupemp")
	private java.lang.String uuidPlantillaCitasInjupemp = "adceb536-8a07-43c7-80c5-6951900170e4";

	@org.kie.api.definition.type.Label("uuidPlantillaConstanciaDeducciones")
	private java.lang.String uuidPlantillaConstDeduc = "1364f513-79d1-4158-8442-5ceb994004fd";

	@org.kie.api.definition.type.Label("uuidPlantillaConstSinDeduc")
	private java.lang.String uuidPlantillaConstSinDeduc = "0020ec36-1e95-4928-a01f-c01b5a7a6258";

	@org.kie.api.definition.type.Label("uuidCarpetaPrincipal")
	private java.lang.String uuidCarpetaPrincipal = "ffb5a821-61f2-42be-a425-2db8f53529e0";

	@org.kie.api.definition.type.Label("nombreCarpetaSolicitudExcusas")
	private java.lang.String nombreCarpetaSolicitudExcusas = "Solicitud de Excusas";

	@org.kie.api.definition.type.Label("msjSuccess")
	private java.lang.String msjSuccess = "success";

	@org.kie.api.definition.type.Label("nombreDocAusencias")
	private java.lang.String nombreDocAusencias = "Solicitud Ausencia";

	@org.kie.api.definition.type.Label("nombreDocLlegadasTarde")
	private java.lang.String nombreDocLlegadasTarde = "Llegadas Tarde";

	@org.kie.api.definition.type.Label("okpSolicitud")
	private java.lang.String okpSolicitud = "solicitudGerh";

	@org.kie.api.definition.type.Label("urlSolicitudes")
	private java.lang.String urlSolicitudes = "http://api-rrhh-expe-solicitudes-desa-api-rrhh-pool.apps.galel.sefin.gob.hn/api";

	@org.kie.api.definition.type.Label("nombreCarpetaSolicitudConstancias")
	private java.lang.String nombreCarpetaSolicitudConstancias = "Constancias Laborales";

	@org.kie.api.definition.type.Label("nombreDocConstanciasDeduc")
	private java.lang.String nombreDocConstanciasDeduc = "Constancia Laboral Con Descuento";

	@org.kie.api.definition.type.Label("nombreDocConstanciasSinDeduc")
	private java.lang.String nombreDocConstanciasSinDeduc = "Constancia Laboral Sin Descuento";

	@org.kie.api.definition.type.Label("extensionDoc")
	private java.lang.String extensionDoc = ".pdf";

	@org.kie.api.definition.type.Label("urlSendMail")
	private java.lang.String urlSendMail = "http://api-rrhh-empl-mail-desa-api-rrhh-pool.apps.galel.sefin.gob.hn/api";

	@org.kie.api.definition.type.Label("urlOpenKm")
	private java.lang.String urlOpenKm = "http://api-info-opkm-servicios-desa-api-rrhh-pool.apps.galel.sefin.gob.hn/api";

	@org.kie.api.definition.type.Label("urlExpediente")
	private java.lang.String urlExpediente = "http://api-rrhh-expe-expediente-desa-api-rrhh-pool.apps.galel.sefin.gob.hn/api";

	@org.kie.api.definition.type.Label("charset")
	private java.lang.String charset = "UTF-8";

	@org.kie.api.definition.type.Label("uuidPlantillaPaseSalida")
	private java.lang.String uuidPlantillaPaseSalida = "cff9032d-5662-432d-924e-98a6d7b7be63";

	@org.kie.api.definition.type.Label("nombreDocPaseSalida")
	private java.lang.String nombreDocPaseSalida = "Pase de Salida";

	@org.kie.api.definition.type.Label("nombreCarpetaSolicitudPase")
	private java.lang.String nombreCarpetaSolicitudPase = "Pase de Salida";

	@org.kie.api.definition.type.Label("nombreDocCitasInjupemp")
	private java.lang.String nombreDocCitasInjupemp = "Cita INJUPEMP";

	@org.kie.api.definition.type.Label("nombreCarpetaSolicitudInjupemp")
	private java.lang.String nombreCarpetaSolicitudInjupemp = "Citas INJUPEMP";

	@org.kie.api.definition.type.Label("mailUriUser")
	private java.lang.String mailUriUser = "/mail/sendMailUser";

	@org.kie.api.definition.type.Label("mailUriGroup")
	private java.lang.String mailUriGroup = "/mail/sendMailGroup";

	@org.kie.api.definition.type.Label("mailTemplatePaseSalida")
	private java.lang.String mailTemplatePaseSalida = "NOTIFICACION_PASE_SALIDA";

	@org.kie.api.definition.type.Label("nombreDocVacaciones")
	private java.lang.String nombreDocVacaciones = "Solicitud de Vacaciones";

	@org.kie.api.definition.type.Label("uuidPlantillaVacaciones")
	private java.lang.String uuidPlantillaVacaciones = "81b1cd66-4477-4b95-883c-cdb0a894164e";

	@org.kie.api.definition.type.Label("nombreCarpetaSolicitudVacaciones")
	private java.lang.String nombreCarpetaSolicitudVacaciones = "Solicitud de Vacaciones";

	@org.kie.api.definition.type.Label("mailTemplateVacaciones")
	private java.lang.String mailTemplateVacaciones = "NOTIFICACION_VACACIONES";

	@org.kie.api.definition.type.Label("mailTemplateAusencias")
	private java.lang.String mailTemplateAusencias = "NOTIFICACION_AUSENCIAS";

	@org.kie.api.definition.type.Label("mailTemplateConstancias")
	private java.lang.String mailTemplateConstancias = "NOTIFICACION_CONSTANCIAS";

	@org.kie.api.definition.type.Label("nombreCarpetaSolicitudRevVacacion")
	private java.lang.String nombreCarpetaSolicitudRevVacacion = "Solicitud de Reversa de Vacaciones";

	@org.kie.api.definition.type.Label("mailTemplateRevVacaciones")
	private java.lang.String mailTemplateRevVacaciones = "NOTIFICACION_REV_VACACIONES";

	@org.kie.api.definition.type.Label("uuidPlantillaRevVacacion")
	private java.lang.String uuidPlantillaRevVacacion;

	@org.kie.api.definition.type.Label("nombreDocRevVacacion")
	private java.lang.String nombreDocRevVacacion = "Reversa de Vacaciones";

	@org.kie.api.definition.type.Label("uuidPlantillaCitasConDeu")
	private java.lang.String uuidPlantillaCitasConDeu = "f4748be0-2a42-4c16-adb6-e6f441acb33e";

	@org.kie.api.definition.type.Label("nombreDocCitasConDeu")
	private java.lang.String nombreDocCitasConDeu = "Cita Consolidacion de Deuda";

	@org.kie.api.definition.type.Label("uuidPlantillaCitasPrAval")
	private java.lang.String uuidPlantillaCitasPrAval = "29f154d1-a672-4c25-a6c1-8488d163af3e";

	@org.kie.api.definition.type.Label("nombreDocCitasPrAval")
	private java.lang.String nombreDocCitasPrAval = "Cita Prestamos con Aval";

	@org.kie.api.definition.type.Label(value = "mailTemplateCitaInjupemp")
	private java.lang.String mailTemplateCitaInjupemp = "NOTIFICACION_INJUPEMP";

	public GlobalVar() {
	}

	public java.lang.String getMail_method() {
		return this.mail_method;
	}

	public void setMail_method(java.lang.String mail_method) {
		this.mail_method = mail_method;
	}

	public java.lang.String getMail_user() {
		return this.mail_user;
	}

	public void setMail_user(java.lang.String mail_user) {
		this.mail_user = mail_user;
	}

	public java.lang.String getMail_attribute() {
		return this.mail_attribute;
	}

	public void setMail_attribute(java.lang.String mail_attribute) {
		this.mail_attribute = mail_attribute;
	}

	public java.lang.String getMail_type() {
		return this.mail_type;
	}

	public void setMail_type(java.lang.String mail_type) {
		this.mail_type = mail_type;
	}

	public java.lang.String getMail_keyvalue() {
		return this.mail_keyvalue;
	}

	public void setMail_keyvalue(java.lang.String mail_keyvalue) {
		this.mail_keyvalue = mail_keyvalue;
	}

	public java.lang.String getDocument_method() {
		return this.document_method;
	}

	public void setDocument_method(java.lang.String document_method) {
		this.document_method = document_method;
	}

	public java.lang.String getDocument_document() {
		return this.document_document;
	}

	public void setDocument_document(java.lang.String document_document) {
		this.document_document = document_document;
	}

	public java.lang.String getDocument_okp() {
		return this.document_okp;
	}

	public void setDocument_okp(java.lang.String document_okp) {
		this.document_okp = document_okp;
	}

	public java.lang.String getDocument_return() {
		return this.document_return;
	}

	public void setDocument_return(java.lang.String document_return) {
		this.document_return = document_return;
	}

	public java.lang.String getProc_url() {
		return this.proc_url;
	}

	public void setProc_url(java.lang.String proc_url) {
		this.proc_url = proc_url;
	}

	public java.lang.String getProc_method() {
		return this.proc_method;
	}

	public void setProc_method(java.lang.String proc_method) {
		this.proc_method = proc_method;
	}

	public java.lang.String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(java.lang.String opcion) {
		this.opcion = opcion;
	}

	public java.lang.String getExpe_method() {
		return this.expe_method;
	}

	public void setExpe_method(java.lang.String expe_method) {
		this.expe_method = expe_method;
	}

	public java.lang.String getDocument_path() {
		return this.document_path;
	}

	public void setDocument_path(java.lang.String document_path) {
		this.document_path = document_path;
	}

	public java.lang.String getUuidPlantillaAusencias() {
		return this.uuidPlantillaAusencias;
	}

	public void setUuidPlantillaAusencias(
			java.lang.String uuidPlantillaAusencias) {
		this.uuidPlantillaAusencias = uuidPlantillaAusencias;
	}

	public java.lang.String getUuidPlantillasLlegadasTarde() {
		return this.uuidPlantillasLlegadasTarde;
	}

	public void setUuidPlantillasLlegadasTarde(
			java.lang.String uuidPlantillasLlegadasTarde) {
		this.uuidPlantillasLlegadasTarde = uuidPlantillasLlegadasTarde;
	}

	public java.lang.String getUuidPlantillaCitasInjupemp() {
		return this.uuidPlantillaCitasInjupemp;
	}

	public void setUuidPlantillaCitasInjupemp(
			java.lang.String uuidPlantillaCitasInjupemp) {
		this.uuidPlantillaCitasInjupemp = uuidPlantillaCitasInjupemp;
	}

	public java.lang.String getUuidPlantillaConstDeduc() {
		return this.uuidPlantillaConstDeduc;
	}

	public void setUuidPlantillaConstDeduc(
			java.lang.String uuidPlantillaConstDeduc) {
		this.uuidPlantillaConstDeduc = uuidPlantillaConstDeduc;
	}

	public java.lang.String getUuidCarpetaPrincipal() {
		return this.uuidCarpetaPrincipal;
	}

	public void setUuidCarpetaPrincipal(java.lang.String uuidCarpetaPrincipal) {
		this.uuidCarpetaPrincipal = uuidCarpetaPrincipal;
	}

	public java.lang.String getNombreCarpetaSolicitudExcusas() {
		return this.nombreCarpetaSolicitudExcusas;
	}

	public void setNombreCarpetaSolicitudExcusas(
			java.lang.String nombreCarpetaSolicitudExcusas) {
		this.nombreCarpetaSolicitudExcusas = nombreCarpetaSolicitudExcusas;
	}

	public java.lang.String getMsjSuccess() {
		return this.msjSuccess;
	}

	public void setMsjSuccess(java.lang.String msjSuccess) {
		this.msjSuccess = msjSuccess;
	}

	public java.lang.String getNombreDocAusencias() {
		return this.nombreDocAusencias;
	}

	public void setNombreDocAusencias(java.lang.String nombreDocAusencias) {
		this.nombreDocAusencias = nombreDocAusencias;
	}

	public java.lang.String getNombreDocLlegadasTarde() {
		return this.nombreDocLlegadasTarde;
	}

	public void setNombreDocLlegadasTarde(
			java.lang.String nombreDocLlegadasTarde) {
		this.nombreDocLlegadasTarde = nombreDocLlegadasTarde;
	}

	public java.lang.String getOkpSolicitud() {
		return this.okpSolicitud;
	}

	public void setOkpSolicitud(java.lang.String okpSolicitud) {
		this.okpSolicitud = okpSolicitud;
	}

	public java.lang.String getUrlSolicitudes() {
		return this.urlSolicitudes;
	}

	public void setUrlSolicitudes(java.lang.String urlSolicitudes) {
		this.urlSolicitudes = urlSolicitudes;
	}

	public java.lang.String getNombreCarpetaSolicitudConstancias() {
		return this.nombreCarpetaSolicitudConstancias;
	}

	public void setNombreCarpetaSolicitudConstancias(
			java.lang.String nombreCarpetaSolicitudConstancias) {
		this.nombreCarpetaSolicitudConstancias = nombreCarpetaSolicitudConstancias;
	}

	public java.lang.String getNombreDocConstanciasDeduc() {
		return this.nombreDocConstanciasDeduc;
	}

	public void setNombreDocConstanciasDeduc(
			java.lang.String nombreDocConstanciasDeduc) {
		this.nombreDocConstanciasDeduc = nombreDocConstanciasDeduc;
	}

	public java.lang.String getNombreDocConstanciasSinDeduc() {
		return this.nombreDocConstanciasSinDeduc;
	}

	public void setNombreDocConstanciasSinDeduc(
			java.lang.String nombreDocConstanciasSinDeduc) {
		this.nombreDocConstanciasSinDeduc = nombreDocConstanciasSinDeduc;
	}

	public java.lang.String getUuidPlantillaConstSinDeduc() {
		return this.uuidPlantillaConstSinDeduc;
	}

	public void setUuidPlantillaConstSinDeduc(
			java.lang.String uuidPlantillaConstSinDeduc) {
		this.uuidPlantillaConstSinDeduc = uuidPlantillaConstSinDeduc;
	}

	public GlobalVar(java.lang.String mail_method, java.lang.String mail_user,
			java.lang.String mail_attribute, java.lang.String mail_type,
			java.lang.String mail_keyvalue, java.lang.String document_method,
			java.lang.String document_document, java.lang.String document_okp,
			java.lang.String document_return, java.lang.String proc_url,
			java.lang.String proc_method, java.lang.String charset,
			java.lang.String opcion, java.lang.String expe_method,
			java.lang.String document_path, java.lang.String urlSendMail,
			java.lang.String urlOpenKm,
			java.lang.String uuidPlantillaAusencias,
			java.lang.String uuidPlantillasLlegadasTarde,
			java.lang.String uuidPlantillaCitasInjupemp,
			java.lang.String uuidPlantillaConstDeduc,
			java.lang.String uuidCarpetaPrincipal,
			java.lang.String urlExpediente,
			java.lang.String nombreCarpetaSolicitudExcusas,
			java.lang.String msjSuccess, java.lang.String nombreDocAusencias,
			java.lang.String nombreDocLlegadasTarde,
			java.lang.String okpSolicitud, java.lang.String urlSolicitudes,
			java.lang.String nombreCarpetaSolicitudConstancias,
			java.lang.String nombreDocConstanciasDeduc,
			java.lang.String nombreDocConstanciasSinDeduc,
			java.lang.String uuidPlantillaConstSinDeduc) {
		this.mail_method = mail_method;
		this.mail_user = mail_user;
		this.mail_attribute = mail_attribute;
		this.mail_type = mail_type;
		this.mail_keyvalue = mail_keyvalue;
		this.document_method = document_method;
		this.document_document = document_document;
		this.document_okp = document_okp;
		this.document_return = document_return;
		this.proc_url = proc_url;
		this.proc_method = proc_method;
		this.charset = charset;
		this.opcion = opcion;
		this.expe_method = expe_method;
		this.document_path = document_path;
		this.urlSendMail = urlSendMail;
		this.urlOpenKm = urlOpenKm;
		this.uuidPlantillaAusencias = uuidPlantillaAusencias;
		this.uuidPlantillasLlegadasTarde = uuidPlantillasLlegadasTarde;
		this.uuidPlantillaCitasInjupemp = uuidPlantillaCitasInjupemp;
		this.uuidPlantillaConstDeduc = uuidPlantillaConstDeduc;
		this.uuidCarpetaPrincipal = uuidCarpetaPrincipal;
		this.urlExpediente = urlExpediente;
		this.nombreCarpetaSolicitudExcusas = nombreCarpetaSolicitudExcusas;
		this.msjSuccess = msjSuccess;
		this.nombreDocAusencias = nombreDocAusencias;
		this.nombreDocLlegadasTarde = nombreDocLlegadasTarde;
		this.okpSolicitud = okpSolicitud;
		this.urlSolicitudes = urlSolicitudes;
		this.nombreCarpetaSolicitudConstancias = nombreCarpetaSolicitudConstancias;
		this.nombreDocConstanciasDeduc = nombreDocConstanciasDeduc;
		this.nombreDocConstanciasSinDeduc = nombreDocConstanciasSinDeduc;
		this.uuidPlantillaConstSinDeduc = uuidPlantillaConstSinDeduc;
	}

	public java.lang.String getExtensionDoc() {
		return this.extensionDoc;
	}

	public void setExtensionDoc(java.lang.String extensionDoc) {
		this.extensionDoc = extensionDoc;
	}

	public java.lang.String getUrlSendMail() {
		return this.urlSendMail;
	}

	public void setUrlSendMail(java.lang.String urlSendMail) {
		this.urlSendMail = urlSendMail;
	}

	public java.lang.String getUrlOpenKm() {
		return this.urlOpenKm;
	}

	public void setUrlOpenKm(java.lang.String urlOpenKm) {
		this.urlOpenKm = urlOpenKm;
	}

	public java.lang.String getUrlExpediente() {
		return this.urlExpediente;
	}

	public void setUrlExpediente(java.lang.String urlExpediente) {
		this.urlExpediente = urlExpediente;
	}

	public java.lang.String getCharset() {
		return this.charset;
	}

	public void setCharset(java.lang.String charset) {
		this.charset = charset;
	}

	public java.lang.String getUuidPlantillaPaseSalida() {
		return this.uuidPlantillaPaseSalida;
	}

	public void setUuidPlantillaPaseSalida(
			java.lang.String uuidPlantillaPaseSalida) {
		this.uuidPlantillaPaseSalida = uuidPlantillaPaseSalida;
	}

	public java.lang.String getNombreDocPaseSalida() {
		return this.nombreDocPaseSalida;
	}

	public void setNombreDocPaseSalida(java.lang.String nombreDocPaseSalida) {
		this.nombreDocPaseSalida = nombreDocPaseSalida;
	}

	public java.lang.String getNombreCarpetaSolicitudPase() {
		return this.nombreCarpetaSolicitudPase;
	}

	public void setNombreCarpetaSolicitudPase(
			java.lang.String nombreCarpetaSolicitudPase) {
		this.nombreCarpetaSolicitudPase = nombreCarpetaSolicitudPase;
	}

	public java.lang.String getNombreDocCitasInjupemp() {
		return this.nombreDocCitasInjupemp;
	}

	public void setNombreDocCitasInjupemp(
			java.lang.String nombreDocCitasInjupemp) {
		this.nombreDocCitasInjupemp = nombreDocCitasInjupemp;
	}

	public java.lang.String getNombreCarpetaSolicitudInjupemp() {
		return this.nombreCarpetaSolicitudInjupemp;
	}

	public void setNombreCarpetaSolicitudInjupemp(
			java.lang.String nombreCarpetaSolicitudInjupemp) {
		this.nombreCarpetaSolicitudInjupemp = nombreCarpetaSolicitudInjupemp;
	}

	public java.lang.String getMailUriUser() {
		return this.mailUriUser;
	}

	public void setMailUriUser(java.lang.String mailUriUser) {
		this.mailUriUser = mailUriUser;
	}

	public java.lang.String getMailUriGroup() {
		return this.mailUriGroup;
	}

	public void setMailUriGroup(java.lang.String mailUriGroup) {
		this.mailUriGroup = mailUriGroup;
	}

	public java.lang.String getMailTemplatePaseSalida() {
		return this.mailTemplatePaseSalida;
	}

	public void setMailTemplatePaseSalida(
			java.lang.String mailTemplatePaseSalida) {
		this.mailTemplatePaseSalida = mailTemplatePaseSalida;
	}

	public java.lang.String getNombreDocVacaciones() {
		return this.nombreDocVacaciones;
	}

	public void setNombreDocVacaciones(java.lang.String nombreDocVacaciones) {
		this.nombreDocVacaciones = nombreDocVacaciones;
	}

	public java.lang.String getUuidPlantillaVacaciones() {
		return this.uuidPlantillaVacaciones;
	}

	public void setUuidPlantillaVacaciones(
			java.lang.String uuidPlantillaVacaciones) {
		this.uuidPlantillaVacaciones = uuidPlantillaVacaciones;
	}

	public java.lang.String getNombreCarpetaSolicitudVacaciones() {
		return this.nombreCarpetaSolicitudVacaciones;
	}

	public void setNombreCarpetaSolicitudVacaciones(
			java.lang.String nombreCarpetaSolicitudVacaciones) {
		this.nombreCarpetaSolicitudVacaciones = nombreCarpetaSolicitudVacaciones;
	}

	public java.lang.String getMailTemplateVacaciones() {
		return this.mailTemplateVacaciones;
	}

	public void setMailTemplateVacaciones(
			java.lang.String mailTemplateVacaciones) {
		this.mailTemplateVacaciones = mailTemplateVacaciones;
	}

	public java.lang.String getMailTemplateAusencias() {
		return this.mailTemplateAusencias;
	}

	public void setMailTemplateAusencias(java.lang.String mailTemplateAusencias) {
		this.mailTemplateAusencias = mailTemplateAusencias;
	}

	public java.lang.String getMailTemplateConstancias() {
		return this.mailTemplateConstancias;
	}

	public void setMailTemplateConstancias(
			java.lang.String mailTemplateConstancias) {
		this.mailTemplateConstancias = mailTemplateConstancias;
	}

	public java.lang.String getNombreCarpetaSolicitudRevVacacion() {
		return this.nombreCarpetaSolicitudRevVacacion;
	}

	public void setNombreCarpetaSolicitudRevVacacion(
			java.lang.String nombreCarpetaSolicitudRevVacacion) {
		this.nombreCarpetaSolicitudRevVacacion = nombreCarpetaSolicitudRevVacacion;
	}

	public java.lang.String getMailTemplateRevVacaciones() {
		return this.mailTemplateRevVacaciones;
	}

	public void setMailTemplateRevVacaciones(
			java.lang.String mailTemplateRevVacaciones) {
		this.mailTemplateRevVacaciones = mailTemplateRevVacaciones;
	}

	public java.lang.String getUuidPlantillaRevVacacion() {
		return this.uuidPlantillaRevVacacion;
	}

	public void setUuidPlantillaRevVacacion(
			java.lang.String uuidPlantillaRevVacacion) {
		this.uuidPlantillaRevVacacion = uuidPlantillaRevVacacion;
	}

	public java.lang.String getNombreDocRevVacacion() {
		return this.nombreDocRevVacacion;
	}

	public void setNombreDocRevVacacion(java.lang.String nombreDocRevVacacion) {
		this.nombreDocRevVacacion = nombreDocRevVacacion;
	}

	public java.lang.String getUuidPlantillaCitasConDeu() {
		return this.uuidPlantillaCitasConDeu;
	}

	public void setUuidPlantillaCitasConDeu(
			java.lang.String uuidPlantillaCitasConDeu) {
		this.uuidPlantillaCitasConDeu = uuidPlantillaCitasConDeu;
	}

	public java.lang.String getNombreDocCitasConDeu() {
		return this.nombreDocCitasConDeu;
	}

	public void setNombreDocCitasConDeu(java.lang.String nombreDocCitasConDeu) {
		this.nombreDocCitasConDeu = nombreDocCitasConDeu;
	}

	public java.lang.String getUuidPlantillaCitasPrAval() {
		return this.uuidPlantillaCitasPrAval;
	}

	public void setUuidPlantillaCitasPrAval(
			java.lang.String uuidPlantillaCitasPrAval) {
		this.uuidPlantillaCitasPrAval = uuidPlantillaCitasPrAval;
	}

	public java.lang.String getNombreDocCitasPrAval() {
		return this.nombreDocCitasPrAval;
	}

	public void setNombreDocCitasPrAval(java.lang.String nombreDocCitasPrAval) {
		this.nombreDocCitasPrAval = nombreDocCitasPrAval;
	}

	public java.lang.String getMailTemplateCitaInjupemp() {
		return this.mailTemplateCitaInjupemp;
	}

	public void setMailTemplateCitaInjupemp(
			java.lang.String mailTemplateCitaInjupemp) {
		this.mailTemplateCitaInjupemp = mailTemplateCitaInjupemp;
	}

	public GlobalVar(java.lang.String mail_method, java.lang.String mail_user,
			java.lang.String mail_attribute, java.lang.String mail_type,
			java.lang.String mail_keyvalue, java.lang.String document_method,
			java.lang.String document_document, java.lang.String document_okp,
			java.lang.String document_return, java.lang.String proc_url,
			java.lang.String proc_method, java.lang.String opcion,
			java.lang.String expe_method, java.lang.String document_path,
			java.lang.String uuidPlantillaAusencias,
			java.lang.String uuidPlantillasLlegadasTarde,
			java.lang.String uuidPlantillaCitasInjupemp,
			java.lang.String uuidPlantillaConstDeduc,
			java.lang.String uuidPlantillaConstSinDeduc,
			java.lang.String uuidCarpetaPrincipal,
			java.lang.String nombreCarpetaSolicitudExcusas,
			java.lang.String msjSuccess, java.lang.String nombreDocAusencias,
			java.lang.String nombreDocLlegadasTarde,
			java.lang.String okpSolicitud, java.lang.String urlSolicitudes,
			java.lang.String nombreCarpetaSolicitudConstancias,
			java.lang.String nombreDocConstanciasDeduc,
			java.lang.String nombreDocConstanciasSinDeduc,
			java.lang.String extensionDoc, java.lang.String urlSendMail,
			java.lang.String urlOpenKm, java.lang.String urlExpediente,
			java.lang.String charset, java.lang.String uuidPlantillaPaseSalida,
			java.lang.String nombreDocPaseSalida,
			java.lang.String nombreCarpetaSolicitudPase,
			java.lang.String nombreDocCitasInjupemp,
			java.lang.String nombreCarpetaSolicitudInjupemp,
			java.lang.String mailUriUser, java.lang.String mailUriGroup,
			java.lang.String mailTemplatePaseSalida,
			java.lang.String nombreDocVacaciones,
			java.lang.String uuidPlantillaVacaciones,
			java.lang.String nombreCarpetaSolicitudVacaciones,
			java.lang.String mailTemplateVacaciones,
			java.lang.String mailTemplateAusencias,
			java.lang.String mailTemplateConstancias,
			java.lang.String nombreCarpetaSolicitudRevVacacion,
			java.lang.String mailTemplateRevVacaciones,
			java.lang.String uuidPlantillaRevVacacion,
			java.lang.String nombreDocRevVacacion,
			java.lang.String uuidPlantillaCitasConDeu,
			java.lang.String nombreDocCitasConDeu,
			java.lang.String uuidPlantillaCitasPrAval,
			java.lang.String nombreDocCitasPrAval,
			java.lang.String mailTemplateCitaInjupemp) {
		this.mail_method = mail_method;
		this.mail_user = mail_user;
		this.mail_attribute = mail_attribute;
		this.mail_type = mail_type;
		this.mail_keyvalue = mail_keyvalue;
		this.document_method = document_method;
		this.document_document = document_document;
		this.document_okp = document_okp;
		this.document_return = document_return;
		this.proc_url = proc_url;
		this.proc_method = proc_method;
		this.opcion = opcion;
		this.expe_method = expe_method;
		this.document_path = document_path;
		this.uuidPlantillaAusencias = uuidPlantillaAusencias;
		this.uuidPlantillasLlegadasTarde = uuidPlantillasLlegadasTarde;
		this.uuidPlantillaCitasInjupemp = uuidPlantillaCitasInjupemp;
		this.uuidPlantillaConstDeduc = uuidPlantillaConstDeduc;
		this.uuidPlantillaConstSinDeduc = uuidPlantillaConstSinDeduc;
		this.uuidCarpetaPrincipal = uuidCarpetaPrincipal;
		this.nombreCarpetaSolicitudExcusas = nombreCarpetaSolicitudExcusas;
		this.msjSuccess = msjSuccess;
		this.nombreDocAusencias = nombreDocAusencias;
		this.nombreDocLlegadasTarde = nombreDocLlegadasTarde;
		this.okpSolicitud = okpSolicitud;
		this.urlSolicitudes = urlSolicitudes;
		this.nombreCarpetaSolicitudConstancias = nombreCarpetaSolicitudConstancias;
		this.nombreDocConstanciasDeduc = nombreDocConstanciasDeduc;
		this.nombreDocConstanciasSinDeduc = nombreDocConstanciasSinDeduc;
		this.extensionDoc = extensionDoc;
		this.urlSendMail = urlSendMail;
		this.urlOpenKm = urlOpenKm;
		this.urlExpediente = urlExpediente;
		this.charset = charset;
		this.uuidPlantillaPaseSalida = uuidPlantillaPaseSalida;
		this.nombreDocPaseSalida = nombreDocPaseSalida;
		this.nombreCarpetaSolicitudPase = nombreCarpetaSolicitudPase;
		this.nombreDocCitasInjupemp = nombreDocCitasInjupemp;
		this.nombreCarpetaSolicitudInjupemp = nombreCarpetaSolicitudInjupemp;
		this.mailUriUser = mailUriUser;
		this.mailUriGroup = mailUriGroup;
		this.mailTemplatePaseSalida = mailTemplatePaseSalida;
		this.nombreDocVacaciones = nombreDocVacaciones;
		this.uuidPlantillaVacaciones = uuidPlantillaVacaciones;
		this.nombreCarpetaSolicitudVacaciones = nombreCarpetaSolicitudVacaciones;
		this.mailTemplateVacaciones = mailTemplateVacaciones;
		this.mailTemplateAusencias = mailTemplateAusencias;
		this.mailTemplateConstancias = mailTemplateConstancias;
		this.nombreCarpetaSolicitudRevVacacion = nombreCarpetaSolicitudRevVacacion;
		this.mailTemplateRevVacaciones = mailTemplateRevVacaciones;
		this.uuidPlantillaRevVacacion = uuidPlantillaRevVacacion;
		this.nombreDocRevVacacion = nombreDocRevVacacion;
		this.uuidPlantillaCitasConDeu = uuidPlantillaCitasConDeu;
		this.nombreDocCitasConDeu = nombreDocCitasConDeu;
		this.uuidPlantillaCitasPrAval = uuidPlantillaCitasPrAval;
		this.nombreDocCitasPrAval = nombreDocCitasPrAval;
		this.mailTemplateCitaInjupemp = mailTemplateCitaInjupemp;
	}

}