package com.sefin_rrhh.pr_rrhh_solicitudes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitudCompleta implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "solicitud")
	private com.sefin_rrhh.pr_rrhh_solicitudes.Solicitud solicitud;
	@org.kie.api.definition.type.Label(value = "camposSolicitud")
	private java.util.List<com.sefin_rrhh.pr_rrhh_solicitudes.SolicitudesCampos> camposSolicitud;

	public SolicitudCompleta() {
	}

	public com.sefin_rrhh.pr_rrhh_solicitudes.Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(
			com.sefin_rrhh.pr_rrhh_solicitudes.Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	public java.util.List<com.sefin_rrhh.pr_rrhh_solicitudes.SolicitudesCampos> getCamposSolicitud() {
		return this.camposSolicitud;
	}

	public void setCamposSolicitud(
			java.util.List<com.sefin_rrhh.pr_rrhh_solicitudes.SolicitudesCampos> camposSolicitud) {
		this.camposSolicitud = camposSolicitud;
	}

	public SolicitudCompleta(
			com.sefin_rrhh.pr_rrhh_solicitudes.Solicitud solicitud,
			java.util.List<com.sefin_rrhh.pr_rrhh_solicitudes.SolicitudesCampos> camposSolicitud) {
		this.solicitud = solicitud;
		this.camposSolicitud = camposSolicitud;
	}

}