package com.sefin_rrhh.pr_rrhh_solicitudes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolicitudesCampos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id_solicitud_campos")
	private Integer id_solicitud_campos;
	@org.kie.api.definition.type.Label("id_solicitud")
	private Integer id_solicitud;
	@org.kie.api.definition.type.Label("key")
	private java.lang.String key;
	@org.kie.api.definition.type.Label("value")
	private java.lang.String value;
	@org.kie.api.definition.type.Label("usu_cre")
	private java.lang.String usu_cre;
	@org.kie.api.definition.type.Label("fec_cre")
	private java.lang.String fec_cre;
	@org.kie.api.definition.type.Label("usu_mod")
	private java.lang.String usu_mod;
	@org.kie.api.definition.type.Label("fec_mod")
	private java.lang.String fec_mod;

	@org.kie.api.definition.type.Label(value = "nombre_campo")
	private java.lang.String nombre_campo;

	public SolicitudesCampos() {
	}

	public java.lang.String getKey() {
		return this.key;
	}

	public void setKey(java.lang.String key) {
		this.key = key;
	}

	public java.lang.String getValue() {
		return this.value;
	}

	public void setValue(java.lang.String value) {
		this.value = value;
	}

	public java.lang.String getUsu_cre() {
		return this.usu_cre;
	}

	public void setUsu_cre(java.lang.String usu_cre) {
		this.usu_cre = usu_cre;
	}

	public java.lang.String getFec_cre() {
		return this.fec_cre;
	}

	public void setFec_cre(java.lang.String fec_cre) {
		this.fec_cre = fec_cre;
	}

	public java.lang.String getUsu_mod() {
		return this.usu_mod;
	}

	public void setUsu_mod(java.lang.String usu_mod) {
		this.usu_mod = usu_mod;
	}

	public java.lang.String getFec_mod() {
		return this.fec_mod;
	}

	public void setFec_mod(java.lang.String fec_mod) {
		this.fec_mod = fec_mod;
	}

	public java.lang.Integer getId_solicitud_campos() {
		return this.id_solicitud_campos;
	}

	public void setId_solicitud_campos(java.lang.Integer id_solicitud_campos) {
		this.id_solicitud_campos = id_solicitud_campos;
	}

	public java.lang.Integer getId_solicitud() {
		return this.id_solicitud;
	}

	public void setId_solicitud(java.lang.Integer id_solicitud) {
		this.id_solicitud = id_solicitud;
	}

	public java.lang.String getNombre_campo() {
		return this.nombre_campo;
	}

	public void setNombre_campo(java.lang.String nombre_campo) {
		this.nombre_campo = nombre_campo;
	}

	public SolicitudesCampos(java.lang.Integer id_solicitud_campos,
			java.lang.Integer id_solicitud, java.lang.String key,
			java.lang.String value, java.lang.String usu_cre,
			java.lang.String fec_cre, java.lang.String usu_mod,
			java.lang.String fec_mod, java.lang.String nombre_campo) {
		this.id_solicitud_campos = id_solicitud_campos;
		this.id_solicitud = id_solicitud;
		this.key = key;
		this.value = value;
		this.usu_cre = usu_cre;
		this.fec_cre = fec_cre;
		this.usu_mod = usu_mod;
		this.fec_mod = fec_mod;
		this.nombre_campo = nombre_campo;
	}

}