package com.sefin_rrhh.pr_rrhh_carga_reloj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RegistrosInfoRelojGerh implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "listaInfoRelojGerh")
	private java.util.List<com.sefin_rrhh.pr_rrhh_carga_reloj.InfoRelojGerh> listaInfoRelojGerh;

	public RegistrosInfoRelojGerh() {
	}

	public java.util.List<com.sefin_rrhh.pr_rrhh_carga_reloj.InfoRelojGerh> getListaInfoRelojGerh() {
		return this.listaInfoRelojGerh;
	}

	public void setListaInfoRelojGerh(
			java.util.List<com.sefin_rrhh.pr_rrhh_carga_reloj.InfoRelojGerh> listaInfoRelojGerh) {
		this.listaInfoRelojGerh = listaInfoRelojGerh;
	}

	public RegistrosInfoRelojGerh(
			java.util.List<com.sefin_rrhh.pr_rrhh_carga_reloj.InfoRelojGerh> listaInfoRelojGerh) {
		this.listaInfoRelojGerh = listaInfoRelojGerh;
	}

}