package com.sefin_rrhh.pr_rrhh_carga_reloj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "state")
	private java.lang.String state;
	@org.kie.api.definition.type.Label(value = "message")
	private java.lang.String message;
	@org.kie.api.definition.type.Label(value = "data")
	private java.lang.Object data;

	public ResponseObject() {
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.Object getData() {
		return this.data;
	}

	public void setData(java.lang.Object data) {
		this.data = data;
	}

	public ResponseObject(java.lang.String state, java.lang.String message,
			java.lang.Object data) {
		this.state = state;
		this.message = message;
		this.data = data;
	}

}